// Mocks generated by Mockito 5.4.5 from annotations
// in medito/test/stats_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:medito/models/local_all_stats.dart' as _i2;
import 'package:medito/services/stats_backup_service.dart' as _i5;
import 'package:medito/services/stats_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalAllStats_0 extends _i1.SmartFake implements _i2.LocalAllStats {
  _FakeLocalAllStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StatsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsService extends _i1.Mock implements _i3.StatsService {
  MockStatsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> hasRecentlySync() =>
      (super.noSuchMethod(
            Invocation.method(#hasRecentlySync, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.LocalAllStats> fetchAllStats() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllStats, []),
            returnValue: _i4.Future<_i2.LocalAllStats>.value(
              _FakeLocalAllStats_0(this, Invocation.method(#fetchAllStats, [])),
            ),
          )
          as _i4.Future<_i2.LocalAllStats>);

  @override
  _i4.Future<void> postStats(_i2.LocalAllStats? stats) =>
      (super.noSuchMethod(
            Invocation.method(#postStats, [stats]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void setBackupServiceForTesting(_i5.StatsBackupService? backupService) =>
      super.noSuchMethod(
        Invocation.method(#setBackupServiceForTesting, [backupService]),
        returnValueForMissingStub: null,
      );
}
