name: medito_widgetbook
description: Component library for Medito
publish_to: none

version: 1.0.0+1

environment:
  sdk: "^3.8.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  medito:
    path: ../
  widgetbook: ^3.22.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.14.1
  widgetbook_generator: ^3.22.0

flutter:
  uses-material-design: true

  assets:
    - ../assets/
    - ../assets/images/
    - ../assets/images/app_icons/

  fonts:
    - family: Google Sans
      fonts:
        - asset: ../assets/fonts/google-sans/GoogleSans-Regular.ttf
          weight: 400
        - asset: ../assets/fonts/google-sans/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: ../assets/fonts/google-sans/GoogleSans-Medium.ttf
          weight: 500
        - asset: ../assets/fonts/google-sans/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: ../assets/fonts/google-sans/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: ../assets/fonts/google-sans/GoogleSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: ../assets/fonts/google-sans/GoogleSans-Bold.ttf
          weight: 700
        - asset: ../assets/fonts/google-sans/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
