// Mocks generated by Mockito 5.4.6 from annotations
// in medito/test/services/stats_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:medito/models/local_all_stats.dart' as _i5;
import 'package:medito/services/network/http_api_service.dart' as _i2;
import 'package:medito/services/stats_backup_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HttpApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpApiService extends _i1.Mock implements _i2.HttpApiService {
  MockHttpApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get retryCountForTesting =>
      (super.noSuchMethod(
            Invocation.getter(#retryCountForTesting),
            returnValue: 0,
          )
          as int);

  @override
  bool get isRefreshingTokenForTesting =>
      (super.noSuchMethod(
            Invocation.getter(#isRefreshingTokenForTesting),
            returnValue: false,
          )
          as bool);

  @override
  set retryCountForTesting(int? value) => super.noSuchMethod(
    Invocation.setter(#retryCountForTesting, value),
    returnValueForMissingStub: null,
  );

  @override
  void addAuthCallback(_i2.AuthStateCallback? callback) => super.noSuchMethod(
    Invocation.method(#addAuthCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void removeAuthCallback(_i2.AuthStateCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#removeAuthCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyForceLogout() => super.noSuchMethod(
    Invocation.method(#notifyForceLogout, []),
    returnValueForMissingStub: null,
  );

  @override
  void setAuthHeader(String? accessToken) => super.noSuchMethod(
    Invocation.method(#setAuthHeader, [accessToken]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthHeader() => super.noSuchMethod(
    Invocation.method(#clearAuthHeader, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> refreshTokenForTesting() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokenForTesting, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getRequest(
    String? path, {
    Map<String, dynamic>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRequest, [path], {#queryParams: queryParams}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> postRequest(String? path, {dynamic body}) =>
      (super.noSuchMethod(
            Invocation.method(#postRequest, [path], {#body: body}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> deleteRequest(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRequest, [path]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addDeviceHeaders(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.method(#addDeviceHeaders, [headers]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<Map<String, dynamic>> diagnoseSecurity() =>
      (super.noSuchMethod(
            Invocation.method(#diagnoseSecurity, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [StatsBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatsBackupService extends _i1.Mock
    implements _i4.StatsBackupService {
  MockStatsBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> backupStats(_i5.LocalAllStats? stats, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#backupStats, [stats, userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i5.LocalAllStats?> getLatestBackup(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestBackup, [userId]),
            returnValue: _i3.Future<_i5.LocalAllStats?>.value(),
          )
          as _i3.Future<_i5.LocalAllStats?>);

  @override
  _i3.Future<List<_i4.StatsBackup>> getAllBackups(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBackups, [userId]),
            returnValue: _i3.Future<List<_i4.StatsBackup>>.value(
              <_i4.StatsBackup>[],
            ),
          )
          as _i3.Future<List<_i4.StatsBackup>>);

  @override
  _i3.Future<List<_i4.StatsBackup>> getAllBackupsAcrossUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBackupsAcrossUsers, []),
            returnValue: _i3.Future<List<_i4.StatsBackup>>.value(
              <_i4.StatsBackup>[],
            ),
          )
          as _i3.Future<List<_i4.StatsBackup>>);

  @override
  _i3.Future<void> clearBackups(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearBackups, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
