// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package meditofoundation.medito.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AudioPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class RepeatMode(val raw: Int) {
  NONE(0),
  ONCE(1),
  INFINITE(2);

  companion object {
    fun ofRaw(raw: Int): RepeatMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class HealthConnectStatus(val raw: Int) {
  AVAILABLE(0),
  NOT_INSTALLED(1),
  NOT_SUPPORTED(2);

  companion object {
    fun ofRaw(raw: Int): HealthConnectStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AudioData (
  val url: String,
  val track: Track
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioData {
      val url = pigeonVar_list[0] as String
      val track = pigeonVar_list[1] as Track
      return AudioData(url, track)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      track,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AudioData
    return AudioPigeonPigeonUtils.deepEquals(this.url, other.url) && AudioPigeonPigeonUtils.deepEquals(this.track, other.track)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.url)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.track)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaybackState (
  val isPlaying: Boolean,
  val isBuffering: Boolean,
  val isSeeking: Boolean,
  val isCompleted: Boolean,
  val position: Long,
  val duration: Long,
  val speed: Speed,
  val volume: Long,
  val track: Track,
  val backgroundSound: BackgroundSound? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackState {
      val isPlaying = pigeonVar_list[0] as Boolean
      val isBuffering = pigeonVar_list[1] as Boolean
      val isSeeking = pigeonVar_list[2] as Boolean
      val isCompleted = pigeonVar_list[3] as Boolean
      val position = pigeonVar_list[4] as Long
      val duration = pigeonVar_list[5] as Long
      val speed = pigeonVar_list[6] as Speed
      val volume = pigeonVar_list[7] as Long
      val track = pigeonVar_list[8] as Track
      val backgroundSound = pigeonVar_list[9] as BackgroundSound?
      return PlaybackState(isPlaying, isBuffering, isSeeking, isCompleted, position, duration, speed, volume, track, backgroundSound)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isPlaying,
      isBuffering,
      isSeeking,
      isCompleted,
      position,
      duration,
      speed,
      volume,
      track,
      backgroundSound,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlaybackState
    return AudioPigeonPigeonUtils.deepEquals(this.isPlaying, other.isPlaying) && AudioPigeonPigeonUtils.deepEquals(this.isBuffering, other.isBuffering) && AudioPigeonPigeonUtils.deepEquals(this.isSeeking, other.isSeeking) && AudioPigeonPigeonUtils.deepEquals(this.isCompleted, other.isCompleted) && AudioPigeonPigeonUtils.deepEquals(this.position, other.position) && AudioPigeonPigeonUtils.deepEquals(this.duration, other.duration) && AudioPigeonPigeonUtils.deepEquals(this.speed, other.speed) && AudioPigeonPigeonUtils.deepEquals(this.volume, other.volume) && AudioPigeonPigeonUtils.deepEquals(this.track, other.track) && AudioPigeonPigeonUtils.deepEquals(this.backgroundSound, other.backgroundSound)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.isPlaying)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.isBuffering)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.isSeeking)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.isCompleted)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.position)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.duration)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.speed)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.volume)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.track)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.backgroundSound)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BackgroundSound (
  val uri: String? = null,
  val title: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BackgroundSound {
      val uri = pigeonVar_list[0] as String?
      val title = pigeonVar_list[1] as String
      return BackgroundSound(uri, title)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      title,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BackgroundSound
    return AudioPigeonPigeonUtils.deepEquals(this.uri, other.uri) && AudioPigeonPigeonUtils.deepEquals(this.title, other.title)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.uri)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.title)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Speed (
  val speed: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Speed {
      val speed = pigeonVar_list[0] as Double
      return Speed(speed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      speed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Speed
    return AudioPigeonPigeonUtils.deepEquals(this.speed, other.speed)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.speed)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Track (
  val id: String,
  val title: String,
  val fileId: String,
  val description: String,
  val imageUrl: String,
  val artist: String? = null,
  val artistUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Track {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val fileId = pigeonVar_list[2] as String
      val description = pigeonVar_list[3] as String
      val imageUrl = pigeonVar_list[4] as String
      val artist = pigeonVar_list[5] as String?
      val artistUrl = pigeonVar_list[6] as String?
      return Track(id, title, fileId, description, imageUrl, artist, artistUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      fileId,
      description,
      imageUrl,
      artist,
      artistUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as Track
    return AudioPigeonPigeonUtils.deepEquals(this.id, other.id) && AudioPigeonPigeonUtils.deepEquals(this.title, other.title) && AudioPigeonPigeonUtils.deepEquals(this.fileId, other.fileId) && AudioPigeonPigeonUtils.deepEquals(this.description, other.description) && AudioPigeonPigeonUtils.deepEquals(this.imageUrl, other.imageUrl) && AudioPigeonPigeonUtils.deepEquals(this.artist, other.artist) && AudioPigeonPigeonUtils.deepEquals(this.artistUrl, other.artistUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.id)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.title)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.fileId)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.description)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.imageUrl)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.artist)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.artistUrl)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CompletionData (
  val trackId: String,
  val duration: Long,
  val fileId: String,
  val guideId: String? = null,
  val timestamp: Long,
  val userToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompletionData {
      val trackId = pigeonVar_list[0] as String
      val duration = pigeonVar_list[1] as Long
      val fileId = pigeonVar_list[2] as String
      val guideId = pigeonVar_list[3] as String?
      val timestamp = pigeonVar_list[4] as Long
      val userToken = pigeonVar_list[5] as String?
      return CompletionData(trackId, duration, fileId, guideId, timestamp, userToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      trackId,
      duration,
      fileId,
      guideId,
      timestamp,
      userToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CompletionData
    return AudioPigeonPigeonUtils.deepEquals(this.trackId, other.trackId) && AudioPigeonPigeonUtils.deepEquals(this.duration, other.duration) && AudioPigeonPigeonUtils.deepEquals(this.fileId, other.fileId) && AudioPigeonPigeonUtils.deepEquals(this.guideId, other.guideId) && AudioPigeonPigeonUtils.deepEquals(this.timestamp, other.timestamp) && AudioPigeonPigeonUtils.deepEquals(this.userToken, other.userToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.trackId)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.duration)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.fileId)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.guideId)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.timestamp)
    result = 31 * result + AudioPigeonPigeonUtils.deepHash(this.userToken)
    return result
  }
}
private open class AudioPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RepeatMode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HealthConnectStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackState.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BackgroundSound.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Speed.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Track.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompletionData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RepeatMode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is HealthConnectStatus -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AudioData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PlaybackState -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is BackgroundSound -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is Speed -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is Track -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CompletionData -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeditoAndroidAudioServiceManager {
  fun startService()
  fun isServiceReady(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by MeditoAndroidAudioServiceManager. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
    /** Sets up an instance of `MeditoAndroidAudioServiceManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeditoAndroidAudioServiceManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAndroidAudioServiceManager.startService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startService()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAndroidAudioServiceManager.isServiceReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isServiceReady{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AudioPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeditoWidgetManager {
  fun pinWidget(widgetType: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by MeditoWidgetManager. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
    /** Sets up an instance of `MeditoWidgetManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeditoWidgetManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoWidgetManager.pinWidget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val widgetTypeArg = args[0] as String
            api.pinWidget(widgetTypeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AudioPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeditoAppIconManager {
  fun getAlternateIconName(callback: (Result<String?>) -> Unit)
  fun setAlternateIconName(iconName: String?, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by MeditoAppIconManager. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
    /** Sets up an instance of `MeditoAppIconManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeditoAppIconManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAppIconManager.getAlternateIconName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAlternateIconName{ result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AudioPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAppIconManager.setAlternateIconName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val iconNameArg = args[0] as String?
            api.setAlternateIconName(iconNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                reply.reply(AudioPigeonPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeditoHealthConnectManager {
  fun getStatus(callback: (Result<HealthConnectStatus>) -> Unit)
  fun hasMindfulnessPermissions(callback: (Result<Boolean>) -> Unit)
  fun requestMindfulnessPermissions(callback: (Result<Boolean>) -> Unit)
  fun writeMindfulnessSession(startEpochMs: Long, endEpochMs: Long, callback: (Result<Boolean>) -> Unit)
  fun openHealthConnectInstall()

  companion object {
    /** The codec used by MeditoHealthConnectManager. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
    /** Sets up an instance of `MeditoHealthConnectManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeditoHealthConnectManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoHealthConnectManager.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getStatus{ result: Result<HealthConnectStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AudioPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoHealthConnectManager.hasMindfulnessPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasMindfulnessPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AudioPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoHealthConnectManager.requestMindfulnessPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestMindfulnessPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AudioPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoHealthConnectManager.writeMindfulnessSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startEpochMsArg = args[0] as Long
            val endEpochMsArg = args[1] as Long
            api.writeMindfulnessSession(startEpochMsArg, endEpochMsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AudioPigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AudioPigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoHealthConnectManager.openHealthConnectInstall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openHealthConnectInstall()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeditoAudioServiceApi {
  fun playAudio(audioData: AudioData): Boolean
  fun playPauseAudio()
  fun stopAudio()
  fun setSpeed(speed: Double)
  fun seekToPosition(position: Long)
  fun skip10SecondsForward()
  fun skip10SecondsBackward()
  fun setRepeatMode(mode: RepeatMode)
  fun setBackgroundSound(uri: String?)
  fun setBackgroundSoundVolume(volume: Double)
  fun stopBackgroundSound()
  fun playBackgroundSound()
  fun pauseBackgroundSound()

  companion object {
    /** The codec used by MeditoAudioServiceApi. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
    /** Sets up an instance of `MeditoAudioServiceApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeditoAudioServiceApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.playAudio$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val audioDataArg = args[0] as AudioData
            val wrapped: List<Any?> = try {
              listOf(api.playAudio(audioDataArg))
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.playPauseAudio$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.playPauseAudio()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.stopAudio$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopAudio()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.setSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val speedArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setSpeed(speedArg)
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.seekToPosition$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val positionArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.seekToPosition(positionArg)
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.skip10SecondsForward$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.skip10SecondsForward()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.skip10SecondsBackward$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.skip10SecondsBackward()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.setRepeatMode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val modeArg = args[0] as RepeatMode
            val wrapped: List<Any?> = try {
              api.setRepeatMode(modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.setBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setBackgroundSound(uriArg)
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.setBackgroundSoundVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val volumeArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setBackgroundSoundVolume(volumeArg)
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.stopBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopBackgroundSound()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.playBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.playBackgroundSound()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.pauseBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pauseBackgroundSound()
              listOf(null)
            } catch (exception: Throwable) {
              AudioPigeonPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MeditoAudioServiceCallbackApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MeditoAudioServiceCallbackApi. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
  }
  fun updatePlaybackState(stateArg: PlaybackState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.medito.MeditoAudioServiceCallbackApi.updatePlaybackState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AudioPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun handleCompletedTrack(completionDataArg: CompletionData, callback: (Result<Boolean>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.medito.MeditoAudioServiceCallbackApi.handleCompletedTrack$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(completionDataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as Boolean
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(AudioPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun reportPlayerError(errorCodeArg: String, messageArg: String, positionMsArg: Long, durationMsArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.medito.MeditoAudioServiceCallbackApi.reportPlayerError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorCodeArg, messageArg, positionMsArg, durationMsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(AudioPigeonPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
