// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class AudioData (
  val url: String,
  val track: Track
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioData {
      val url = pigeonVar_list[0] as String
      val track = pigeonVar_list[1] as Track
      return AudioData(url, track)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      track,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaybackState (
  val isPlaying: Boolean,
  val isBuffering: Boolean,
  val isSeeking: Boolean,
  val isCompleted: Boolean,
  val position: Long,
  val duration: Long,
  val speed: Speed,
  val volume: Long,
  val track: Track,
  val backgroundSound: BackgroundSound? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaybackState {
      val isPlaying = pigeonVar_list[0] as Boolean
      val isBuffering = pigeonVar_list[1] as Boolean
      val isSeeking = pigeonVar_list[2] as Boolean
      val isCompleted = pigeonVar_list[3] as Boolean
      val position = pigeonVar_list[4] as Long
      val duration = pigeonVar_list[5] as Long
      val speed = pigeonVar_list[6] as Speed
      val volume = pigeonVar_list[7] as Long
      val track = pigeonVar_list[8] as Track
      val backgroundSound = pigeonVar_list[9] as BackgroundSound?
      return PlaybackState(isPlaying, isBuffering, isSeeking, isCompleted, position, duration, speed, volume, track, backgroundSound)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isPlaying,
      isBuffering,
      isSeeking,
      isCompleted,
      position,
      duration,
      speed,
      volume,
      track,
      backgroundSound,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BackgroundSound (
  val uri: String? = null,
  val title: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BackgroundSound {
      val uri = pigeonVar_list[0] as String?
      val title = pigeonVar_list[1] as String
      return BackgroundSound(uri, title)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      title,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Speed (
  val speed: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Speed {
      val speed = pigeonVar_list[0] as Double
      return Speed(speed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      speed,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Track (
  val id: String,
  val title: String,
  val description: String,
  val imageUrl: String,
  val artist: String? = null,
  val artistUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Track {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val description = pigeonVar_list[2] as String
      val imageUrl = pigeonVar_list[3] as String
      val artist = pigeonVar_list[4] as String?
      val artistUrl = pigeonVar_list[5] as String?
      return Track(id, title, description, imageUrl, artist, artistUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      description,
      imageUrl,
      artist,
      artistUrl,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CompletionData (
  val trackId: String,
  val duration: Long,
  val fileId: String,
  val guideId: String? = null,
  val timestamp: Long,
  val userToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CompletionData {
      val trackId = pigeonVar_list[0] as String
      val duration = pigeonVar_list[1] as Long
      val fileId = pigeonVar_list[2] as String
      val guideId = pigeonVar_list[3] as String?
      val timestamp = pigeonVar_list[4] as Long
      val userToken = pigeonVar_list[5] as String?
      return CompletionData(trackId, duration, fileId, guideId, timestamp, userToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      trackId,
      duration,
      fileId,
      guideId,
      timestamp,
      userToken,
    )
  }
}
private open class AudioPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaybackState.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BackgroundSound.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Speed.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Track.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CompletionData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AudioData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PlaybackState -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BackgroundSound -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is Speed -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is Track -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CompletionData -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeditoAndroidAudioServiceManager {
  fun startService()

  companion object {
    /** The codec used by MeditoAndroidAudioServiceManager. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
    /** Sets up an instance of `MeditoAndroidAudioServiceManager` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeditoAndroidAudioServiceManager?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAndroidAudioServiceManager.startService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startService()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MeditoAudioServiceApi {
  fun playAudio(audioData: AudioData): Boolean
  fun playPauseAudio()
  fun stopAudio()
  fun setSpeed(speed: Double)
  fun seekToPosition(position: Long)
  fun skip10SecondsForward()
  fun skip10SecondsBackward()
  fun setBackgroundSound(uri: String?)
  fun setBackgroundSoundVolume(volume: Double)
  fun stopBackgroundSound()
  fun playBackgroundSound()
  fun pauseBackgroundSound()

  companion object {
    /** The codec used by MeditoAudioServiceApi. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
    /** Sets up an instance of `MeditoAudioServiceApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MeditoAudioServiceApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.playAudio$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val audioDataArg = args[0] as AudioData
            val wrapped: List<Any?> = try {
              listOf(api.playAudio(audioDataArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.playPauseAudio$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.playPauseAudio()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.stopAudio$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopAudio()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.setSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val speedArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setSpeed(speedArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.seekToPosition$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val positionArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.seekToPosition(positionArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.skip10SecondsForward$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.skip10SecondsForward()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.skip10SecondsBackward$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.skip10SecondsBackward()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.setBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String?
            val wrapped: List<Any?> = try {
              api.setBackgroundSound(uriArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.setBackgroundSoundVolume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val volumeArg = args[0] as Double
            val wrapped: List<Any?> = try {
              api.setBackgroundSoundVolume(volumeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.stopBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopBackgroundSound()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.playBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.playBackgroundSound()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.medito.MeditoAudioServiceApi.pauseBackgroundSound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pauseBackgroundSound()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MeditoAudioServiceCallbackApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MeditoAudioServiceCallbackApi. */
    val codec: MessageCodec<Any?> by lazy {
      AudioPigeonPigeonCodec()
    }
  }
  fun updatePlaybackState(stateArg: PlaybackState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.medito.MeditoAudioServiceCallbackApi.updatePlaybackState$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun handleCompletedTrack(completionDataArg: CompletionData, callback: (Result<Boolean>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.medito.MeditoAudioServiceCallbackApi.handleCompletedTrack$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(completionDataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as Boolean
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
