# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'


      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - run: flutter --version

      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: flutter channel stable

      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: flutter upgrade

      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: flutter pub get

      - name: Check Flutter and Dart versions
        run: |
          flutter --version
          DART_PATH=$(dirname $(which dart))
          echo "DART_PATH=$DART_PATH" >> $GITHUB_ENV

      - name: Clone and build dart-code-metrics
        run: |
          git clone https://github.com/dart-code-checker/dart-code-metrics.git
          cd dart-code-metrics
          flutter pub get
          ${{ env.DART_PATH }}/dart compile exe bin/metrics.dart -o dart_code_metrics

      - name: Run dart-code-metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          cd dart-code-metrics
          ls -a .
          ./dart_code_metrics analyze --reporter=github \
            --github-workflow=${{ github.workflow }} \
            --github-run-id=${{ github.run_id }} \
            --github-repository=${{ github.repository }} \
            --github-pull-request=${{ github.event.pull_request.number }} \
            --github-token=$GITHUB_TOKEN

      - name: "Create a dummy auth.dart"
        run: echo -e "var BASE_URL = ''; \n var SENTRY_URL = ''; \nvar CONTENT_TOKEN = '';\nvar INIT_TOKEN = '';" > .env

      - run: flutter clean && flutter pub get

      - name: Run Riverpod generator
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - run: flutter analyze --no-fatal-warnings --no-fatal-infos .

      - run: flutter test